
image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: >
      echo "Do Before" >> /tmp/StartLog
      g++ test.cpp -o test >> /tmp/StartLog
    init: >
      echo "Do Init" >> /tmp/StartLog
      g++ test.cpp -o test >> /tmp/StartLog
    command: >
      echo "Do Command" >> /tmp/StartLog
      g++ test.cpp -o test >> /tmp/StartLog

vscode:
  extensions:
    - webfreak.debug