image:
  file: .gitpod.Dockerfile


# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: |
      /workspace/TestDevSpaces/bin/setup-dev-env
      . ~/.bashrc
hosts:
  name1: 127.0.0.1
  name2: 127.0.0.2
  name3: 127.0.0.1
  name7: 127.0.0.1
  myip6: ::1
vscode:
  extensions:
    - https://devspaces-extensions-bucket.s3.us-east-2.amazonaws.com/jupyter-2021.8.1013163132_vsixhub.com.vsix
    - https://github.com/microsoft/vscode-cpptools/releases/download/1.4.1/cpptools-linux.vsix
    - https://github.com/microsoft/vscode-cpptools/releases/download/1.4.1/cpptools-linux-aarch64.vsix
    - webfreak.debug
    - humao.rest-client
