tasks:
  - command: |
      echo "cat /etc/hosts to see added hosts"
hosts:
  name1: 127.0.0.1
  name2: 127.0.0.2
  fqdn.name.com: 127.0.0.1
  www.google.com: 127.0.0.1
  myip6: ::1
  fqdn.ip6.com: ::1
