
# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: >
      echo "Do Before" >> /workspace/StartLog
      g++ test.cpp -o test >> /workspace/StartLog
    init: >
      echo "Do Init" >> /workspace/StartLog
      g++ test.cpp -o test >> /workspace/StartLog
    command: >
      echo "Do Command" >> /workspace/StartLog
      g++ test.cpp -o test >> /workspace/StartLog

vscode:
  extensions:
    - webfreak.debug